apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::868237635331:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-EIO1Dslqux3I
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::868237635331:role/UdacityFlaskDeployCBKubectlRole
      username: build     
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-25T11:03:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1264"
  uid: 09d61d0c-8cc5-4ce8-b2d5-cf2a1c01a109
